version: 2
jobs:
    build_deploy:
        working_directory: ~/konec-dejin
        docker:
            - image: circleci/node:10.16.0-browsers
        steps:
            - checkout:
                path: ~/konec-dejin
            - run:
                name: Show current branch
                command: echo ${CIRCLE_BRANCH} 
            - run:
                name: Show current directory
                command: pwd    
            - run:
                name: Install dependencies app
                command: cd app && npm install
            - run:
                name: Building app
                command: cd app && npm run build-prod  
            - run:
                name: Install dependencies swiss
                command: cd swiss && npm install
            - run:
                name: Building swiss
                command: cd swiss && npm run build-prod      
            - run:
                name: Install dependencies
                command: cd functions && npm install
            - run:
                name: Install Firebase
                command: sudo npm install -g firebase-tools 
            - run:
                name: Deploy Master to Firebase
                command: firebase deploy --token=$FIREBASE_TOKEN       
            
workflows:
  version: 2

  build_deploy:
    jobs:
      - build_deploy