name: Push to master

on:
  push:
    branches:
      - main

concurrency:
  group: master
  cancel-in-progress: true

jobs:
  deploy-or-die:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Deploy or die
        run: |
            cd web
            npm install
            npm run build-prod 
            cd ../app
            npm install
            npm run build-prod  
            cd ../swiss
            npm install
            npm run build-prod
            cd ../functions
            npm install
            cd .. 
            sudo npm install -g firebase-tools@9.10.0
            sudo npm install -g firebase-bolt
            firebase deploy --token=$FIREBASE_TOKEN 
        env: 
            FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
